; HTime Specification v1.0.0
; All times assumed to be local (no timezone support).

htime          = datetime [offset]
               / offset

datetime       = "now"
               / weekday               ; mon
               / month                 ; jan
               / time                  ; 3p 304p 15 1504
               / time-weekday          ; 15,mon / 1504,mon / 304p,mon
               / month-day             ; jan2
               / time-month-day        ; 15,jan2 / 1504,jan2 / 304p,jan2
               / year                  ; ,2006
               / month-year            ; jan,2006
               / month-day-year        ; jan2,2006
               / time-month-day-year   ; 15,jan2,2006 / 304p,jan2,2006

weekday        = "mon" / "tue" / "wed" / "thu" / "fri" / "sat" / "sun"

month          = month-short / month-long

month-short    = "jan" / "feb" / "mar" / "apr" / "may" / "jun" 
               / "jul" / "aug" / "sep" / "oct" / "nov" / "dec"
               / "Jan" / "Feb" / "Mar" / "Apr" / "May" / "Jun" 
               / "Jul" / "Aug" / "Sep" / "Oct" / "Nov" / "Dec"

month-long    = "january", "february", "march", "april", "may",
              / "june", "july", "august", "september", "october",
              / "november", "december"
              / "January", "February", "March", "April", "May",
              / "June", "July", "August", "September", "October",
              / "November", "December"

year           = "," 4DIGIT                         ; ,2006

time           = hour / hour-ampm / hour-min / hour-min-ampm

offset         = 
               / ("s" / "m" / "h" / "d" / "w" / "y")

go-dur         = [("-" /"+")] 1*(go-dur-units / cal-dur-units)

go-dur-units   = FLOAT ("ns" / "us" / "µs" / "ms" / "s" / "m" / "h")

cal-dur-units  = FLOAT ("d" / "w") 

month-day      =  month day-month               ; jan2

time-weekday   = time "," weekday               ; jan2,304p

month-day-time = month-day "," time             ; jan2,15

day-month      = NINE                           ; 1-9 
               / (("1" / "2") DIGIT)            ; 10 - 29
               / ("3" ("0","1"))                ; 30 - 31

hour-min       = hour min

hour           = ("0" NINE)                     ; 01 - 09
               / ("1" DIGIT)                    ; 11 - 19
               / ("2" ("0" / "1" / "2" / "3"))  ; 20 - 23

minute         = ("0" NINE)                     ; 01 - 09
               / (FIVE DIGIT)                   ; 11 - 59

hour-ampm      = TWELVE ("a" / "p")

hour-min-ampm  = TWELVE ("a" / "p")
 
timezone       = (("-" / "+") 2DIGIT)           ; -07
               / "Z"                            ; Z

TWELVE         = NINE / ("1" ("0" / "1" / "2"))

NINE           = "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9"

FIVE           = "1" / "2" / "3" / "4" / "5"

FLOAT          = 1*DIGIT ["." 1*DIGIT]
